#!/bin/sh -f

#set -x

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

. ../mgr/build_header

cppflags="${cppflags} -I../CoinGL/include"

libs="${libs} -L../CoinGL/${build_dir} -lourex_CoinGL"

plugin=Coin_SWIG_Python
pyname=Coin_SWIG_Python

use_Python=yes
. ${exlib_mgr}/use_Python

use_GL=yes
. ${exlib_mgr}/use_GL

if [ ${build_compile} = "yes" ] ; then

cxxfiles="${cxxfiles} ./source/SWIG.cxx"

cppflags="${cppflags} -I."

if [ ${build_visual} = "yes" ] ; then
  cppflags="${cppflags} /wd4244 /wd4700 /wd4049"
else
  cppflags="${cppflags} -w"
fi

. ${inlib_mgr}/build_compile

fi # end build_compile

if [ ${build_plugin} = "yes" ] ; then . ${inlib_mgr}/build_plugin; fi

. ${inlib_mgr}/build_clean
