#ifndef OnX_OnX_gl2ps_h
#define OnX_OnX_gl2ps_h

/* 
 gl2ps-1.2.3.
 The gl2ps code is prefixed by OnX_ in order
 to avoid clashes with other gl2ps code that may come at link
 time from other channels.
*/

#define gl2psBeginPage OnX_gl2psBeginPage
#define gl2psEndPage OnX_gl2psEndPage
#define gl2psText OnX_gl2psText
#define gl2psEnable OnX_gl2psEnable
#define gl2psDisable OnX_gl2psDisable
#define gl2psPointSize OnX_gl2psPointSize
#define gl2psLineWidth OnX_gl2psLineWidth
#define gl2psNumShadeColors OnX_gl2psNumShadeColors
#define gl2psDrawPixels OnX_gl2psDrawPixels
#define gl2psBeginViewport OnX_gl2psBeginViewport
#define gl2psEndViewport OnX_gl2psEndViewport

#define gl2psMsg OnX_gl2psMsg
#define gl2psMalloc OnX_gl2psMalloc
#define gl2psRealloc OnX_gl2psRealloc
#define gl2psFree OnX_gl2psFree
#define gl2psListRealloc OnX_gl2psListRealloc
#define gl2psListCreate OnX_gl2psListCreate
#define gl2psListDelete OnX_gl2psListDelete
#define gl2psListAdd OnX_gl2psListAdd
#define gl2psListNbr OnX_gl2psListNbr
#define gl2psListPointer OnX_gl2psListPointer
#define gl2psListSort OnX_gl2psListSort
#define gl2psListAction OnX_gl2psListAction
#define gl2psListActionInverse OnX_gl2psListActionInverse
#define gl2psComparePointPlane OnX_gl2psComparePointPlane
#define gl2psPsca OnX_gl2psPsca
#define gl2psPvec OnX_gl2psPvec
#define gl2psNorm OnX_gl2psNorm
#define gl2psGetNormal OnX_gl2psGetNormal
#define gl2psGetPlane OnX_gl2psGetPlane
#define gl2psCutEdge OnX_gl2psCutEdge
#define gl2psCreateSplitPrimitive OnX_gl2psCreateSplitPrimitive
#define gl2psAddIndex OnX_gl2psAddIndex
#define gl2psGetIndex OnX_gl2psGetIndex
#define gl2psTestSplitPrimitive OnX_gl2psTestSplitPrimitive
#define gl2psSplitPrimitive OnX_gl2psSplitPrimitive
#define gl2psDivideQuad OnX_gl2psDivideQuad
#define gl2psCompareDepth OnX_gl2psCompareDepth
#define gl2psTrianglesFirst OnX_gl2psTrianglesFirst
#define gl2psFindRoot OnX_gl2psFindRoot
#define gl2psFreePrimitive OnX_gl2psFreePrimitive
#define gl2psAddPrimitiveInList OnX_gl2psAddPrimitiveInList
#define gl2psFreeBspTree OnX_gl2psFreeBspTree
#define gl2psGreater OnX_gl2psGreater
#define gl2psLess OnX_gl2psLess
#define gl2psBuildBspTree OnX_gl2psBuildBspTree
#define gl2psTraverseBspTree OnX_gl2psTraverseBspTree
#define gl2psGetPlaneFromPoints OnX_gl2psGetPlaneFromPoints
#define gl2psFreeBspImageTree OnX_gl2psFreeBspImageTree
#define gl2psCheckPoint OnX_gl2psCheckPoint
#define gl2psAddPlanesInBspTreeImage OnX_gl2psAddPlanesInBspTreeImage
#define gl2psCheckPrimitive OnX_gl2psCheckPrimitive
#define gl2psCreateSplitPrimitive2D OnX_gl2psCreateSplitPrimitive2D
#define gl2psSplitPrimitive2D OnX_gl2psSplitPrimitive2D
#define gl2psAddInImageTree OnX_gl2psAddInImageTree
#define gl2psAddInImage OnX_gl2psAddInImage
#define gl2psAddBoundaryInList OnX_gl2psAddBoundaryInList
#define gl2psBuildPolygonBoundary OnX_gl2psBuildPolygonBoundary
#define gl2psAddPolyPrimitive OnX_gl2psAddPolyPrimitive
#define gl2psGetVertex OnX_gl2psGetVertex
#define gl2psParseFeedbackBuffer OnX_gl2psParseFeedbackBuffer
#define gl2psSameColor OnX_gl2psSameColor
#define gl2psVertsSameColor OnX_gl2psVertsSameColor
#define gl2psPrintPostScriptHeader OnX_gl2psPrintPostScriptHeader
#define gl2psPrintPostScriptColor OnX_gl2psPrintPostScriptColor
#define gl2psResetPostScriptColor OnX_gl2psResetPostScriptColor
#define gl2psPrintPostScriptPrimitive OnX_gl2psPrintPostScriptPrimitive
#define gl2psPrintPostScriptFooter OnX_gl2psPrintPostScriptFooter
#define gl2psPrintTeXHeader OnX_gl2psPrintTeXHeader
#define gl2psPrintTeXPrimitive OnX_gl2psPrintTeXPrimitive
#define gl2psPrintTeXFooter OnX_gl2psPrintTeXFooter

#define gl2psPrintPostScriptBeginViewport OnX_gl2psPrintPostScriptBeginViewport
#define gl2psPrintPostScriptEndViewport OnX_gl2psPrintPostScriptEndViewport

#define gl2psWriteByte OnX_gl2psWriteByte
#define gl2psGetRGB OnX_gl2psGetRGB
#define gl2psPrintPostScriptPixmap OnX_gl2psPrintPostScriptPixmap
#define gl2psListReset OnX_gl2psListReset
#define gl2psAddInBspImageTree OnX_gl2psAddInBspImageTree
#define gl2psPrintPrimitives OnX_gl2psPrintPrimitives
#define gl2psPrintTeXBeginViewport OnX_gl2psPrintTeXBeginViewport
#define gl2psPrintTeXEndViewport OnX_gl2psPrintTeXEndViewport

#define gl2psAdaptVertexForBlending OnX_gl2psAdaptVertexForBlending
#define gl2psAssignTriangleProperties OnX_gl2psAssignTriangleProperties
#define gl2psBlendFunc OnX_gl2psBlendFunc
#define gl2psClosePDFDataStream OnX_gl2psClosePDFDataStream
#define gl2psCopyPixmap OnX_gl2psCopyPixmap
#define gl2psCopyPrimitive OnX_gl2psCopyPrimitive
#define gl2psCopyText OnX_gl2psCopyText
#define gl2psDrawImageMap OnX_gl2psDrawImageMap
#define gl2psFillTriangleFromPrimitive OnX_gl2psFillTriangleFromPrimitive
#define gl2psFreeImagemap OnX_gl2psFreeImagemap
#define gl2psFreePixmap OnX_gl2psFreePixmap
#define gl2psFreeText OnX_gl2psFreeText
#define gl2psOpenPDFDataStream OnX_gl2psOpenPDFDataStream
#define gl2psOpenPDFDataStreamWritePreface OnX_gl2psOpenPDFDataStreamWritePreface
#define gl2psPDFRectHull OnX_gl2psPDFRectHull
#define gl2psPDFgroupListDelete OnX_gl2psPDFgroupListDelete
#define gl2psPDFgroupListInit OnX_gl2psPDFgroupListInit
#define gl2psPDFgroupListWriteFontResources OnX_gl2psPDFgroupListWriteFontResources
#define gl2psPDFgroupListWriteGStateResources OnX_gl2psPDFgroupListWriteGStateResources
#define gl2psPDFgroupListWriteMainStream OnX_gl2psPDFgroupListWriteMainStream
#define gl2psPDFgroupListWriteObjects OnX_gl2psPDFgroupListWriteObjects
#define gl2psPDFgroupListWriteShaderResources OnX_gl2psPDFgroupListWriteShaderResources
#define gl2psPDFgroupListWriteVariableResources OnX_gl2psPDFgroupListWriteVariableResources
#define gl2psPDFgroupListWriteXObjectResources OnX_gl2psPDFgroupListWriteXObjectResources
#define gl2psPDFgroupObjectInit OnX_gl2psPDFgroupObjectInit
#define gl2psPDFstacksInit OnX_gl2psPDFstacksInit
#define gl2psPrintPDFBeginViewport OnX_gl2psPrintPDFBeginViewport
#define gl2psPrintPDFCatalog OnX_gl2psPrintPDFCatalog
#define gl2psPrintPDFCompressorType OnX_gl2psPrintPDFCompressorType
#define gl2psPrintPDFDataStreamLength OnX_gl2psPrintPDFDataStreamLength
#define gl2psPrintPDFEndViewport OnX_gl2psPrintPDFEndViewport
#define gl2psPrintPDFFillColor OnX_gl2psPrintPDFFillColor
#define gl2psPrintPDFFooter OnX_gl2psPrintPDFFooter
#define gl2psPrintPDFGSObject OnX_gl2psPrintPDFGSObject
#define gl2psPrintPDFHeader OnX_gl2psPrintPDFHeader
#define gl2psPrintPDFInfo OnX_gl2psPrintPDFInfo
#define gl2psPrintPDFLineWidth OnX_gl2psPrintPDFLineWidth
#define gl2psPrintPDFOpenPage OnX_gl2psPrintPDFOpenPage
#define gl2psPrintPDFPages OnX_gl2psPrintPDFPages
#define gl2psPrintPDFPixmap OnX_gl2psPrintPDFPixmap
#define gl2psPrintPDFPixmapStreamData OnX_gl2psPrintPDFPixmapStreamData
#define gl2psPrintPDFPrimitive OnX_gl2psPrintPDFPrimitive
#define gl2psPrintPDFShader OnX_gl2psPrintPDFShader
#define gl2psPrintPDFShaderExtGS OnX_gl2psPrintPDFShaderExtGS
#define gl2psPrintPDFShaderMask OnX_gl2psPrintPDFShaderMask
#define gl2psPrintPDFShaderSimpleExtGS OnX_gl2psPrintPDFShaderSimpleExtGS
#define gl2psPrintPDFShaderStreamData OnX_gl2psPrintPDFShaderStreamData
#define gl2psPrintPDFShaderStreamDataAlpha OnX_gl2psPrintPDFShaderStreamDataAlpha
#define gl2psPrintPDFShaderStreamDataCoord OnX_gl2psPrintPDFShaderStreamDataCoord
#define gl2psPrintPDFShaderStreamDataRGB OnX_gl2psPrintPDFShaderStreamDataRGB
#define gl2psPrintPDFStrokeColor OnX_gl2psPrintPDFStrokeColor
#define gl2psPrintPDFText OnX_gl2psPrintPDFText
#define gl2psPrintPostScriptImagemap OnX_gl2psPrintPostScriptImagemap
#define gl2psPrintf OnX_gl2psPrintf
#define gl2psPutPDFImage OnX_gl2psPutPDFImage
#define gl2psPutPDFText OnX_gl2psPutPDFText
#define gl2psSetLastColor OnX_gl2psSetLastColor
#define gl2psSortOutTrianglePDFgroup OnX_gl2psSortOutTrianglePDFgroup
#define gl2psSupportedBlendMode OnX_gl2psSupportedBlendMode
#define gl2psTextOpt OnX_gl2psTextOpt
#define gl2psWriteBigEndian OnX_gl2psWriteBigEndian
#define gl2psPrintDash OnX_gl2psPrintDash
#define gl2psRescaleAndOffset OnX_gl2psRescaleAndOffset

#define gl2ps OnX_gl2ps

#include "gl2ps.h"

#endif
