#!/bin/sh -f

#set -x

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

inlib_mgr=../../../inexlib/inlib/mgr
exlib_mgr=../../../inexlib/exlib/mgr
ourex_mgr=../../../inexlib/ourex/mgr

build_pack=slash-config

. ${ourex_mgr}/build_header

if [ ${build_app} = "yes" ] ; then

  cppflags="${cppflags} -I.."
  cppflags="${cppflags} -I${inlib_mgr}/.."

  objs=
  app_exe=slash-config
  app_src=../applications/Slash_config.cxx
  . ${inlib_mgr}/build_app

fi

. ${inlib_mgr}/build_clean
