#!/bin/sh -f

run_what=

build_args=
while test $# -ge 1 ; do
  case $1 in
    -*) build_args="${build_args} $1";;  
     *) run_what=$1;;  
  esac
  shift
done

. ../mgr/build_header

#////////////////////////////////////
#/// plugins : //////////////////////
#////////////////////////////////////
PYTHONPATH=
PYTHONPATH="${PYTHONPATH}:${build_path}"
PYTHONPATH="${PYTHONPATH}:../CoinPython/${build_dir}"
PYTHONPATH="${PYTHONPATH}:../CoinXt/${build_dir}"
#////////////////////////////////////
#/// .py scripts : //////////////////
#////////////////////////////////////
PYTHONPATH="${PYTHONPATH}:./scripts/Python"
PYTHONPATH="${PYTHONPATH}:../CoinPython/scripts"
PYTHONPATH="${PYTHONPATH}:../CoinXt/py"

# for examples/Python/plotter.py
PYTHONPATH="${PYTHONPATH}:${exlib_mgr}/${build_dir}"
PYTHONPATH="${PYTHONPATH}:${exlib_mgr}/../exlib/py"

export PYTHONPATH

#////////////////////////////////////
#/// shared libs : //////////////////
#////////////////////////////////////
ld_path=
ld_path="${ld_path}:../CoinXt/${build_dir}"
ld_path="${ld_path}:../HEPVis/${build_dir}"
ld_path="${ld_path}:../CoinGL/${build_dir}"
ld_path="${ld_path}:../freetype/${build_dir}"
ld_path="${ld_path}:../jpeg/${build_dir}"
ld_path="${ld_path}:../png/${build_dir}"
ld_path="${ld_path}:../zlib/${build_dir}"

. ${inlib_mgr}/build_ld_library_path

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

use_Python=yes
. ${exlib_mgr}/use_Python

#////////////////////////////////////
#/// run : //////////////////////////
#////////////////////////////////////

TTFPATH=./fonts
export TTFPATH

if [ "${run_what}" = "" ] ; then run_what=cube; fi

${py_exe} ./examples/Python/${run_what}.py

