#!/bin/sh -f

#set -x

from=/barrand/externals/SoXt_1_2_2/SoXt
sogui=${from}/src/Inventor/Xt/common
to=/barrand/OpenScientist/dev/CoinXt/v1r122p0

# Template devices :
./gui_in ${sogui}/devices/SoGuiSpaceball.cpp.in ${from}  ${to}/src/Inventor/Xt/devices Xt SoXtSpaceballCommon.cpp
./gui_in ${sogui}/devices/SoGuiDevice.cpp.in ${from}  ${to}/src/Inventor/Xt/devices Xt SoXtDeviceCommon.cpp
./gui_in ${sogui}/devices/SoGuiMouse.cpp.in ${from}  ${to}/src/Inventor/Xt/devices Xt SoXtMouseCommon.cpp
./gui_in ${sogui}/devices/SoGuiKeyboard.cpp.in ${from}  ${to}/src/Inventor/Xt/devices Xt SoXtKeyboardCommon.cpp
./gui_in ${sogui}/devices/SoGuiInputFocus.cpp.in ${from}  ${to}/src/Inventor/Xt/devices Xt SoXtInputFocusCommon.cpp

# Template viewers :
./gui_in ${sogui}/viewers/SoGuiConstrainedViewer.cpp.in ${from}  ${to}/src/Inventor/Xt/viewers Xt
./gui_in ${sogui}/viewers/SoGuiExaminerViewer.cpp.in ${from}  ${to}/src/Inventor/Xt/viewers Xt
./gui_in ${sogui}/viewers/SoGuiFlyViewer.cpp.in ${from}  ${to}/src/Inventor/Xt/viewers Xt
./gui_in ${sogui}/viewers/SoGuiFullViewer.cpp.in ${from}  ${to}/src/Inventor/Xt/viewers Xt
./gui_in ${sogui}/viewers/SoGuiPlaneViewer.cpp.in ${from}  ${to}/src/Inventor/Xt/viewers Xt
./gui_in ${sogui}/viewers/SoGuiWalkViewer.cpp.in ${from}  ${to}/src/Inventor/Xt/viewers Xt
./gui_in ${sogui}/viewers/SoGuiViewer.cpp.in ${from}  ${to}/src/Inventor/Xt/viewers Xt

# Template widgets :
./gui_in ${sogui}/widgets/SoGuiPopupMenu.cpp.in ${from}  ${to}/src/Inventor/Xt/widgets Xt
./gui_in ${sogui}/widgets/SoAnyThumbWheel.cpp.in ${from}  ${to}/src/Inventor/Xt/widgets Xt
#./gui_in ${sogui}/SoGuiCursors.cpp.in ${from}  ${to}/src/Inventor/Xt Xt

# Template nodes :
./gui_in ${sogui}/nodes/ClickCounter.cpp.in ${from}  ${to}/src/Inventor/Xt/nodes Xt ClickCounter.cpp
./gui_in ${sogui}/nodes/ColorEditor.cpp.in ${from}  ${to}/src/Inventor/Xt/nodes Xt ColorEditor.cpp
./gui_in ${sogui}/nodes/Frame.cpp.in ${from}  ${to}/src/Inventor/Xt/nodes Xt Frame.cpp
./gui_in ${sogui}/nodes/Image.cpp.in ${from}  ${to}/src/Inventor/Xt/nodes Xt Image.cpp
./gui_in ${sogui}/nodes/Label.cpp.in ${from}  ${to}/src/Inventor/Xt/nodes Xt Label.cpp
./gui_in ${sogui}/nodes/MaterialEditor.cpp.in ${from}  ${to}/src/Inventor/Xt/nodes Xt MaterialEditor.cpp
./gui_in ${sogui}/nodes/Nodes.cpp.in ${from}  ${to}/src/Inventor/Xt/nodes Xt SoGuiNodes.cpp
./gui_in ${sogui}/nodes/Pane.cpp.in ${from}  ${to}/src/Inventor/Xt/nodes Xt Pane.cpp
./gui_in ${sogui}/nodes/Position.cpp.in ${from}  ${to}/src/Inventor/Xt/nodes Xt Position.cpp
./gui_in ${sogui}/nodes/RadioButton.cpp.in ${from}  ${to}/src/Inventor/Xt/nodes Xt RadioButton.cpp
./gui_in ${sogui}/nodes/SceneTexture2.cpp.in ${from}  ${to}/src/Inventor/Xt/nodes Xt SceneTexture2.cpp
./gui_in ${sogui}/nodes/Slider1.cpp.in ${from}  ${to}/src/Inventor/Xt/nodes Xt Slider1.cpp
./gui_in ${sogui}/nodes/Slider2.cpp.in ${from}  ${to}/src/Inventor/Xt/nodes Xt Slider2.cpp
./gui_in ${sogui}/nodes/ToggleButton.cpp.in ${from}  ${to}/src/Inventor/Xt/nodes Xt ToggleButton.cpp
./gui_in ${sogui}/nodes/Translation.cpp.in ${from}  ${to}/src/Inventor/Xt/nodes Xt Translation.cpp
./gui_in ${sogui}/nodes/ViewpointWrapper.cpp.in ${from}  ${to}/src/Inventor/Xt/nodes Xt ViewpointWrapper.cpp
./gui_in ${sogui}/nodes/ViewportFix.cpp.in ${from}  ${to}/src/Inventor/Xt/nodes Xt ViewportFix.cpp

# Template engines :
./gui_in ${sogui}/engines/Engines.cpp.in ${from} ${to}/src/Inventor/Xt/engines Xt Engines.cpp
./gui_in ${sogui}/engines/Format.cpp.in ${from} ${to}/src/Inventor/Xt/engines Xt Format.cpp
./gui_in ${sogui}/engines/RadioGroup.cpp.in ${from} ${to}/src/Inventor/Xt/engines Xt RadioGroup.cpp

# Template editors :
./gui_in ${sogui}/editors/MaterialEditor.cpp.in ${from} ${to}/src/Inventor/Xt/editors Xt SoXtMaterialEditor.cpp
./gui_in ${sogui}/editors/ColorEditor.cpp.in ${from} ${to}/src/Inventor/Xt/editors Xt SoXtColorEditor.cpp

# Template general :
./gui_in ${sogui}/SoAny.cpp.in ${from}  ${to}/src/Inventor/Xt Xt
./gui_in ${sogui}/SoAnyMaterialList.cpp.in ${from}  ${to}/src/Inventor/Xt Xt
./gui_in ${sogui}/SoAnyMaterialListBuiltins.cpp.in ${from}  ${to}/src/Inventor/Xt Xt
./gui_in ${sogui}/SoGuiCommon.cpp.in ${from}  ${to}/src/Inventor/Xt Xt
./gui_in ${sogui}/SoGuiObject.cpp.in ${from}  ${to}/src/Inventor/Xt Xt
./gui_in ${sogui}/SoGuiRenderArea.cpp.in ${from}  ${to}/src/Inventor/Xt Xt
./gui_in ${sogui}/SoGuiGLWidgetCommon.cpp.in ${from}  ${to}/src/Inventor/Xt Xt
./gui_in ${sogui}/SoGuiCursor.cpp.in ${from}  ${to}/src/Inventor/Xt Xt
./gui_in ${sogui}/SoGuiComponentCommon.cpp.in ${from}  ${to}/src/Inventor/Xt Xt

#./gui_in ${sogui}/spwinput_x11.cpp.in ${from} ${to}/src/Inventor/Xt Xt

# Not templated files :
find ${from}/src -name "*.cpp" -exec ./cp_cpp {} ${from} ${to} \;
find ${from}/src -name "Xt*.cpp" -exec ./cp_cpp {} ${from} ${to} \;

find ../src -name 'all-*.cpp' -exec /bin/rm {} \;
find ../src -name 'all*.c' -exec /bin/rm {} \;



