#!/bin/sh -f

from=/barrand/externals/SoXt_1_2_2/SoXt
to=/barrand/OpenScientist/dev/CoinXt/v1r122p0

find ${from}/data/materials -name "*.h.in" -exec ./materials_h_in {} ${from} ${to} \;

find ${from}/data/materials -name "*.[0-9]*" -exec ./materials {} ${from} ${to} \;
