#!/bin/sh -f

#set -x

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

. ../mgr/build_header

cppflags="${cppflags} -I../CoinGL/include"

# libs for the apps :
libs="${libs} ${build_path}/${libname}.a"
libs="${libs} ../CoinGL/${build_dir}/libourex_CoinGL.a"

use_archive=yes
use_gtkglarea=yes
. ${exlib_mgr}/use_gtkglarea

use_GL=yes
use_gtk=yes
use_GLX=yes
use_X11=yes

. ${exlib_mgr}/use_GL
. ${exlib_mgr}/use_gtk
. ${exlib_mgr}/use_X11

use_thread=yes
use_dl=yes
. ${exlib_mgr}/use_thread
. ${exlib_mgr}/use_dl

if [ ${build_compile} = "yes" ] ; then

find ./src/Inventor/Gtk -name '*.cpp' >> cpp_tmp

cppflags="${cppflags} -I./include"
cppflags="${cppflags} -I./src"
cppflags="${cppflags} -I./data"

cppflags="${cppflags} -DHAVE_CONFIG_H"
cppflags="${cppflags} -DSOGTK_INTERNAL"
cppflags="${cppflags} -DSOGTK_DEBUG=0"

if [ ${build_visual} = "yes" ] ; then
  cppflags="${cppflags} -DSOGTK_MAKE_DLL"
else
  cppflags="${cppflags} -w"
  cppflags="${cppflags} -D_REENTRANT"
  cppflags="${cppflags} -DPIC"
  cppflags="${cppflags} -fPIC -fno-exceptions -fno-common"
  cppflags="${cppflags} -Wno-unused -Wno-multichar"
  cppflags="${cppflags} -Woverloaded-virtual"
fi

#if [ `uname` = "Darwin" ] ; then
#  # if building bundle -multiply_defined suppress
#fi

. ${inlib_mgr}/build_compile

fi # end build_compile

if [ ${build_archive} = "yes" ] ; then . ${inlib_mgr}/build_archive; fi

if [ ${build_app} = "yes" ] ; then

#  if [ ${build_visual} = "yes" ] ; then
#    ccflags="${ccflags} /I./include"
#  else
#    ccflags="${ccflags} -I./include"
#  fi

  cppflags="${cppflags} -I./include"

  objs=
  app_exe=test_cube
  app_src=./tests/CoinGtk_test_cube.cpp
  . ${inlib_mgr}/build_app

fi

. ${inlib_mgr}/build_clean
