#!/bin/sh -f

#set -x

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

inlib_mgr=../../../inexlib/inlib/mgr
ourex_mgr=../../../inexlib/ourex/mgr
. ${ourex_mgr}/build_header

build_pack=Minuit

if [ ${build_compile} = "yes" ] ; then

cppflags="${cppflags} -I.."

/bin/rm -f cpp_tmp
find ../src -name '*.cpp' -print >> cpp_tmp

libname=libosc_Minuit

. ${inlib_mgr}/build_compile

fi # end build_compile
 
if [ ${build_archive} = "yes" ] ; then . ${inlib_mgr}/build_archive; fi

. ${inlib_mgr}/build_clean
