#!/bin/sh -f

#set -x

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

inlib_mgr=../../../inexlib/inlib/mgr
exlib_mgr=../../../inexlib/exlib/mgr
ourex_mgr=../../../inexlib/ourex/mgr

build_pack=backcomp

. ${ourex_mgr}/build_header

if [ ${build_compile} = "yes" ] ; then

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

cxxfiles=
cxxfiles="${cxxfiles} ../Lib/dummy.cxx"

. ${inlib_mgr}/build_compile

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

fi # end build_compile

libname=libLibZip 
if [ ${build_archive} = "yes" ] ; then . ${inlib_mgr}/build_archive; fi

. ${inlib_mgr}/build_clean
