/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.28
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OnX;

public class Main {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Main(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Main obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      OnXJNI.delete_Main(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Main(boolean create_UI, boolean show_UI, String[] arg2) {
    this(OnXJNI.new_Main(create_UI, show_UI, arg2), true);
  }

  public IUI createUI(boolean arg0) {
    long cPtr = OnXJNI.Main_createUI__SWIG_0(swigCPtr, arg0);
    return (cPtr == 0) ? null : new IUI(cPtr, false);
  }

  public IUI createUI() {
    long cPtr = OnXJNI.Main_createUI__SWIG_1(swigCPtr);
    return (cPtr == 0) ? null : new IUI(cPtr, false);
  }

  public boolean isValid() {
    return OnXJNI.Main_isValid(swigCPtr);
  }

  public int steer() {
    return OnXJNI.Main_steer(swigCPtr);
  }

  public void show() {
    OnXJNI.Main_show(swigCPtr);
  }

  public IUI ui() {
    long cPtr = OnXJNI.Main_ui(swigCPtr);
    return (cPtr == 0) ? null : new IUI(cPtr, false);
  }

  public ISession session() {
    long cPtr = OnXJNI.Main_session(swigCPtr);
    return (cPtr == 0) ? null : new ISession(cPtr, false);
  }

  public void setOnXFile(String arg0) {
    OnXJNI.Main_setOnXFile(swigCPtr, arg0);
  }

  public boolean loadInterpreter(String arg0, boolean aQuiet) {
    return OnXJNI.Main_loadInterpreter__SWIG_0(swigCPtr, arg0, aQuiet);
  }

  public boolean loadInterpreter(String arg0) {
    return OnXJNI.Main_loadInterpreter__SWIG_1(swigCPtr, arg0);
  }

}
