/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OnX;

public class OnX implements OnXConstants {
  public static ISession Slash_create_session(String[] args) {
    long cPtr = OnXJNI.Slash_create_session(args);
    return (cPtr == 0) ? null : new ISession(cPtr, false);
  }

  public static SWIGTYPE_p_std__ostream Slash_cout() {
    return new SWIGTYPE_p_std__ostream(OnXJNI.Slash_cout(), false);
  }

  public static SWIGTYPE_p_std__ostream Slash_cerr() {
    return new SWIGTYPE_p_std__ostream(OnXJNI.Slash_cerr(), false);
  }

  public static ISession OnX_cast_ISession(String aString) {
    long cPtr = OnXJNI.OnX_cast_ISession(aString);
    return (cPtr == 0) ? null : new ISession(cPtr, false);
  }

}
