#!/bin/sh -f

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

. ../mgr/build_header

cppflags="${cppflags} -I../CoinPython"

cppflags="${cppflags} -I./include"
libs="${libs} -L../CoinXt/${build_dir} -lourex_CoinXt"

plugin=CoinXt_SWIG_Python
pyname=CoinXt_SWIG_Python

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////
use_Python=yes
use_CoinGL=yes
use_Xm=yes
use_X11=yes
use_GLX=yes
use_GL=yes

. ${exlib_mgr}/use_Python
. ${exlib_mgr}/use_CoinGL
. ${exlib_mgr}/use_Xm
. ${exlib_mgr}/use_X11
. ${exlib_mgr}/use_GL

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

if [ ${build_compile} = "yes" ] ; then

cppfiles="${cppfiles} ./py/SWIG.cpp"

#cppflags="${cppflags} -I./include"

#if [ ${build_visual} = "yes" ] ; then
#  cppflags="${cppflags} /wd4244 /wd4700 /wd4049"
#else
#  cppflags="${cppflags} -w"
#fi

. ${inlib_mgr}/build_compile

fi # end build_compile

if [ ${build_plugin} = "yes" ] ; then . ${inlib_mgr}/build_plugin; fi

. ${inlib_mgr}/build_clean
