#!/bin/sh -f
#
#  To produce wrappers using SWIG.
#

SWIG_native_version=1.3.33
SWIG_home=/usr/local/SWIG/${SWIG_native_version}
SWIG_exe="${SWIG_home}/bin/swig"

if test ! -x "${SWIG_exe}" ; then
  echo "swig program not found."
  exit
fi

#set -x

do_python=no
do_tcl=no
do_java=no

if test $# = 0 ; then
 do_python=yes
 do_tcl=no
 do_java=no
fi


if test $# = 1 ; then
 if test $1 = python ; then
   do_python=yes
 fi
 if test $1 = py ; then
   do_python=yes
 fi
 if test $1 = tcl ; then
   do_tcl=yes
 fi
 if test $1 = java ; then
   do_java=yes
 fi
fi


# Python :
if test ${do_python} = yes ; then
  echo "swig for Python..."

  pivy_home=/Users/barrand/private/dev/install/Pivy-0.3.0

  if test ! -d $pivy_home ; then
    echo "Directory ${pivy_home} not found."
    exit
  fi

  incs=""
  incs="${incs} -I../../Slash"
  incs="${incs} -I../../OnX/include"

  incs="${incs} -I${pivy_home} -I${pivy_home}/fake_headers"
  incs="${incs} -I../../CoinGL/include"
  incs="${incs} -I../../CoinPython"
  incs="${incs} -I../../HEPVis/include"
  incs="${incs} -I${pivy_home}/interfaces"
  incs="${incs} -I../../CoinPython/source"
  incs="${incs} -I../../HEPVis/source/SWIG"
  incs="${incs}  -I../../inlib -I../../inlib/inlib/histo -I../../inlib/inlib"

  incs="${incs} -I../source/SWIG"

  flags="-includeall -modern -D__PIVY__"
  flags="${flags} -w302,306,307,312,389,361,362,467,503,509,510"
  flags="${flags} -fcompact"

  out_file=../source/Python/OnX_SWIG_Python.ic
  eval $SWIG_exe -interface OnX_SWIG_Python -python -c++ ${flags} ${incs} -o ${out_file} ../source/SWIG/OnX_SWIG.i
  /bin/mv ../source/Python/OnX.py ../scripts/Python/.
  sed -e 's#PyErr_Format(PyExc_RuntimeError, mesg)#PyErr_Format(PyExc_RuntimeError, "%s",mesg)#g' ${out_file} > tmp;mv tmp ${out_file}
  /bin/rm -f tmp
fi

incs=""
incs="${incs} -I../../Slash"
incs="${incs} -I../../OnX/include"
incs="${incs} -I../source/SWIG"

# tcl :
if test ${do_tcl} = yes ; then
  echo "swig for Tcl..."
  flags="-Wall -fcompact"
  eval $SWIG_exe -tcl -c++ ${flags} ${incs} -o ../source/Tcl/OnX_SWIG_Tcl.ic ../source/SWIG/OnX_SWIG.i
fi

# java :
if test ${do_java} = yes ; then
  echo "swig for java..."
  find ../source/Java/OnX -name '*.java' -exec /bin/rm {} \;
  flags="-Wall -fcompact"
  eval $SWIG_exe -java -c++ ${flags} ${incs} -o ../source/Java/OnX_SWIG_Java.ic  -package OnX -outdir ../source/Java/OnX ../source/SWIG/OnX_SWIG.i
fi

# XML :
#cp ../source/SWIG/OnX_SWIG.i SWIG.i
#$SWIG_exe -xml -c++ ${incs} SWIG.i
#/bin/mv SWIG_wrap.xml ../source/XML/XML_SWIG.xml
#touch ../source/XML/XML_SWIG.xml
#/bin/rm -f SWIG.i

