/**************************************************************************
 *
 *  This file is part of the Coin GUI binding libraries.
 *  Copyright (C) 2000 by Systems in Motion.  All rights reserved.
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public License
 *  version 2.1 as published by the Free Software Foundation.  See the
 *  file LICENSE.LGPL at the root directory of the distribution for
 *  more details.
 *
 *  If you want to use Coin GUI bindings for applications not compatible
 *  with the LGPL, please contact SIM to acquire a Professional Edition
 *  License.
 *
 *  Systems in Motion, Prof Brochs gate 6, N-7030 Trondheim, NORWAY
 *  http://www.sim.no/ support@sim.no Voice: +47 22114160 Fax: +47 22207097
 *
 **************************************************************************/

/* Autogenerated from materials/artdeco/artdeco.0 */

#ifndef SOQT_GLASS18_IV_H
#define SOQT_GLASS18_IV_H

static const char glass18_iv[] =
  "#Inventor V1.0 ascii\n"
  "\n"
  "Material {\n"
  "	ambientColor	0.86048676 0.86048676 0.89999237\n"
  "	diffuseColor	0.40076295 0.44191653 0.45909819\n"
  "	specularColor	0.81467917 0.35497062 0.31079575\n"
  "	emissiveColor	0 0 0\n"
  "	shininess	0.12727550\n"
  "	transparency	0.24324406\n"
  "}\n"
;

#endif /* ! SOQT_ARTDECO0_IV_H */
