/**************************************************************************
 *
 *  This file is part of the Coin GUI binding libraries.
 *  Copyright (C) 2000 by Systems in Motion.  All rights reserved.
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public License
 *  version 2.1 as published by the Free Software Foundation.  See the
 *  file LICENSE.LGPL at the root directory of the distribution for
 *  more details.
 *
 *  If you want to use Coin GUI bindings for applications not compatible
 *  with the LGPL, please contact SIM to acquire a Professional Edition
 *  License.
 *
 *  Systems in Motion, Prof Brochs gate 6, N-7030 Trondheim, NORWAY
 *  http://www.sim.no/ support@sim.no Voice: +47 22114160 Fax: +47 22207097
 *
 **************************************************************************/

/* Autogenerated from materials/artdeco/artdeco.0 */

#ifndef SOQT_GLASS28_IV_H
#define SOQT_GLASS28_IV_H

static const char glass28_iv[] =
  "#Inventor V1.0 ascii\n"
  "\n"
  "Material {\n"
  "	ambientColor	0.13281452 0.13614099 0.13614099\n"
  "	diffuseColor	0.56667429 0.58086518 0.58088044\n"
  "	specularColor	0.61020828 0.75460440 0.94209201\n"
  "	emissiveColor	0 0 0\n"
  "	shininess	0.16818493\n"
  "	transparency	0.19691767\n"
  "}\n"
;

#endif /* ! SOQT_ARTDECO0_IV_H */
