#!/bin/sh -f

from=/home/barrand/Coin/SoQt
to=/projects/CoinQt/v1

find ${from}/data/materials -name "*.h.in" -exec ./materials_h_in {} ${from} ${to} \;

find ${from}/data/materials -name "*.[0-9]*" -exec ./materials {} ${from} ${to} \;
