#!/bin/sh -f

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

inlib_mgr=../../../inexlib/inlib/mgr
exlib_mgr=../../../inexlib/exlib/mgr
ourex_mgr=../../../inexlib/ourex/mgr

. ${ourex_mgr}/build_header

plugin=OnXLabKUIP

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////
if [ ${build_compile} = "yes" ] ; then

cppflags="${cppflags} -I${inlib_mgr}/.."

cppflags="${cppflags} -I../../AIDA/v3r2p1"
cppflags="${cppflags} -I../../Slash"
cppflags="${cppflags} -I../../amanip/src/cpp"

cxxfiles=
cxxfiles="${cxxfiles} ../source/KUIP/KuipWrap.cxx"

cfiles=
cfiles="${cfiles} ../source/KUIP/KuipWrapCDF.c"

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

use_KUIP=yes
KUIP_home=${ourex_mgr}/../KUIP
. ${exlib_mgr}/use_KUIP

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

. ${inlib_mgr}/build_compile

fi # end build_compile
 
if [ ${build_plugin} = "yes" ] ; then . ${inlib_mgr}/build_plugin; fi

. ${inlib_mgr}/build_clean
