#!/bin/sh -f

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

. ../mgr/build_header

cppflags="${cppflags} -I../CoinPython"
cppflags="${cppflags} -I${inlib_mgr}/.."

libs="${libs} -L../HEPVis/${build_dir} -lourex_HEPVis"

plugin=HEPVis_SWIG_Python
pyname=HEPVis_SWIG_Python

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////
use_Python=yes
use_CoinGL=yes
use_GL=yes
use_png=yes
use_jpeg=yes
use_freetype=yes
use_zlib=yes

. ${exlib_mgr}/use_Python
. ${exlib_mgr}/use_CoinGL
. ${exlib_mgr}/use_GL
. ${exlib_mgr}/use_png
. ${exlib_mgr}/use_jpeg
. ${exlib_mgr}/use_freetype
. ${exlib_mgr}/use_zlib

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

if [ ${build_compile} = "yes" ] ; then

# get source code in HEPVis :
cxxfiles="${cxxfiles} ../HEPVis/source/Python/HEPVis_SWIG_Python.cxx"

cppflags="${cppflags} -I../HEPVis/include"

if [ ${build_visual} = "yes" ] ; then
  cppflags="${cppflags} /wd4244 /wd4700 /wd4049"
else
  cppflags="${cppflags} -w"
fi

. ${inlib_mgr}/build_compile

fi # end build_compile

if [ ${build_plugin} = "yes" ] ; then . ${inlib_mgr}/build_plugin; fi

. ${inlib_mgr}/build_clean
