#!/bin/sh -f

#set -x

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

. ../mgr/build_header

if [ ${build_compile} = "yes" ] ; then

echo ./src/tidbits.c >> c_tmp
echo ./src/engines/evaluator.c >> c_tmp
echo ./src/engines/evaluator_tab.c >> c_tmp

find ./src/threads -name '*.c' -print >> c_tmp
find ./src/glue -name '*.c' -print >> c_tmp
find ./src/base -name '*.c' -print >> c_tmp
find ./src/errors -name '*.c' -print >> c_tmp
find ./src/misc -name '*.c' -print >> c_tmp
find ./src/fonts -name '*.c' -print >> c_tmp
find ./src/io -name '*.c' -print >> c_tmp

find ./src/threads -name '*.cpp' -print >> cpp_tmp
find ./src/glue -name '*.cpp' -print >> cpp_tmp
find ./src/actions -name '*.cpp' -print >> cpp_tmp
find ./src/base -name '*.cpp' -print >> cpp_tmp
find ./src/upgraders -name '*.cpp' -print >> cpp_tmp
find ./src/bundles -name '*.cpp' -print >> cpp_tmp
find ./src/caches -name '*.cpp' -print >> cpp_tmp
find ./src/details -name '*.cpp' -print >> cpp_tmp
find ./src/draggers -name '*.cpp' -print >> cpp_tmp
find ./src/elements -name '*.cpp' -print >> cpp_tmp
#find ./src/elements/GL -name '*.cpp' -print >> cpp_tmp
find ./src/engines -name '*.cpp' -print >> cpp_tmp

find ./src/errors -name '*.cpp' -print >> cpp_tmp
find ./src/events -name '*.cpp' -print >> cpp_tmp
find ./src/fields -name '*.cpp' -print >> cpp_tmp
find ./src/manips -name '*.cpp' -print >> cpp_tmp
find ./src/lists -name '*.cpp' -print >> cpp_tmp
find ./src/nodekits -name '*.cpp' -print >> cpp_tmp
find ./src/nodes -name '*.cpp' -print >> cpp_tmp
find ./src/projectors -name '*.cpp' -print >> cpp_tmp
find ./src/sensors -name '*.cpp' -print >> cpp_tmp
find ./src/misc -name '*.cpp' -print >> cpp_tmp
find ./src/3ds -name '*.cpp' -print >> cpp_tmp
find ./src/hardcopy -name '*.cpp' -print >> cpp_tmp
find ./src/shapenodes -name '*.cpp' -print >> cpp_tmp
find ./src/fonts -name '*.cpp' -print >> cpp_tmp
find ./src/collision -name '*.cpp' -print >> cpp_tmp
find ./src/io -name '*.cpp' -print >> cpp_tmp
find ./src/vrml97 -name '*.cpp' -print >> cpp_tmp
  
# 2.5.0 :
find ./src/geo -name '*.cpp' -print >> cpp_tmp
find ./src/shaders -name '*.cpp' -print >> cpp_tmp
find ./src/shadows -name '*.cpp' -print >> cpp_tmp

#///////////////////////////////////////////////////////
#/// to avoid ranlib warnings, do not      /////////////
#/// include files that induce empty .o :  /////////////
#///////////////////////////////////////////////////////
#if [ ${build_verbose} = yes ] ; then echo "filter out some files ...";fi

exclude=
exclude="${exclude} spidermonkey threads_dummy glue_dummy SbIntList"
exclude="${exclude} SbList SbStringList SoEngineOutputList"
exclude="${exclude} SoFieldList SoJavaScriptEngine"
exclude="${exclude} 3dsLoader SoStream"
#exclude="${exclude} SoOffscreenAGLData SoOffscreenGLXData SoOffscreenWGLData"
if [ ${build_visual} = "no" ] ; then
  exclude="${exclude} win32api"
fi

for exc in ${exclude} ; do
  grep -v ${exc} c_tmp   > tmp_0;/bin/mv tmp_0 c_tmp
  grep -v ${exc} cpp_tmp > tmp_0;/bin/mv tmp_0 cpp_tmp
done

#///////////////////////////////////////////////////////
#///////////////////////////////////////////////////////
#///////////////////////////////////////////////////////

gen_flags="${gen_flags} -I./src"
gen_flags="${gen_flags} -I."
gen_flags="${gen_flags} -I./include"
gen_flags="${gen_flags} -I./include/Inventor/annex"

# Darwin, Linux : from Coin_2_4_4 build system on a Panther.
  
gen_flags="${gen_flags} -DHAVE_CONFIG_H"
gen_flags="${gen_flags} -DCOIN_INTERNAL"
gen_flags="${gen_flags} -DCOIN_DEBUG=0"

if [ ${build_visual} = "yes" ] ; then
  gen_flags="${gen_flags} -DCOIN_MAKE_DLL"
else
  gen_flags="${gen_flags} -D_REENTRANT"
  gen_flags="${gen_flags} -DPIC"
  #-DCOIN_THREADSAFE
  gen_flags="${gen_flags} -fPIC -fno-exceptions"
  gen_flags="${gen_flags} -fno-builtin -finline-functions"
  gen_flags="${gen_flags} -Wno-unused -Wno-multichar -Wreturn-type"
  gen_flags="${gen_flags} -Wchar-subscripts -Wparentheses"
  cppflags="${cppflags} -Woverloaded-virtual"
fi

if [ `uname` = "Darwin" ] ; then
  gen_flags="${gen_flags}  -fno-common"
  if [ ${build_gnu} = "yes" ] ; then
    gen_flags="${gen_flags} -no-cpp-precomp"
  fi
  # put the below to rm warnings in dl.c and gl_agl.c :
  gen_flags="${gen_flags} -w"
fi

ccflags="${ccflags} ${gen_flags}"
cppflags="${cppflags} ${gen_flags}"

use_GL=yes
use_zip=yes
use_zlib=yes

. ${exlib_mgr}/use_GL

. ${exlib_mgr}/use_zip
. ${exlib_mgr}/use_zlib

. ${inlib_mgr}/build_compile

fi # end build_compile

# CoinGL is crowded with statics of the nodes dictionary, then
# we need the shared lib in case CoinGL is used in an app using
# various plugins linked to CoinGL. (It is the case in the
# osc_vis context).

if [ ${build_archive} = "yes" ] ; then . ${inlib_mgr}/build_archive; fi

. ${inlib_mgr}/build_clean
