#!/bin/sh -f

#set -x

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

inlib_mgr=../../../inexlib/inlib/mgr
exlib_mgr=../../../inexlib/exlib/mgr
ourex_mgr=../../../inexlib/ourex/mgr

build_pack=BatchLabZebra

. ${ourex_mgr}/build_header

if [ ${build_compile} = "yes" ] ; then

. ${exlib_mgr}/use_f77

cppflags="${cppflags} -I.."
cppflags="${cppflags} -I../../Slash"
cppflags="${cppflags} -I../../AIDA/v3r2p1"
cppflags="${cppflags} -I${inlib_mgr}/.."
cppflags="${cppflags} -I../../Lib/include"
cppflags="${cppflags} -I../../amanip/src/cpp"

cxxfiles="${cxxfiles} ../source/Zebra/CHBOOK.cxx"
cxxfiles="${cxxfiles} ../source/Zebra/Zebra_Histogram.cxx"
cxxfiles="${cxxfiles} ../source/Zebra/Zebra_Tuple.cxx"
cxxfiles="${cxxfiles} ../source/Zebra/Zebra_Tree.cxx"
cxxfiles="${cxxfiles} ../source/Zebra/Zebra_Manager.cxx"
cxxfiles="${cxxfiles} ../source/Zebra/Zebra.cxx"

f77files="${f77files} ../source/Zebra/close.f"
f77files="${f77files} ../source/Zebra/setpawc.f"
f77files="${f77files} ../source/Zebra/hntvar2.f"
f77files="${f77files} ../source/Zebra/hisid.f"

#f77files="${f77files} ../source/Zebra/hids.f"

libs=" ${libs} -L../../Lib/mgr/${build_dir} -lLibUtils"

if [ `uname` = Darwin ] ; then
  if [ ${build_m32} = no ] ; then
    echo 'build_plugin_BatchLabZebra : must be built with -m32.'
    exit
  fi
  # we don't have a -m64 -lgfortran.
  #if [ `uname` = Darwin ] ; then  
  #  f77flags=-m64
  #fi
  cfiles="${cfiles} ${ourex_mgr}/../hbook/hdummy.c"
  libs="${libs} -lgfortran"
else
  use_cernlib=yes
  . ${exlib_mgr}/use_cernlib
fi

. ${inlib_mgr}/build_compile

fi # end build_compile
 
if [ ${build_plugin} = "yes" ] ; then . ${inlib_mgr}/build_plugin; fi

. ${inlib_mgr}/build_clean
