#!/bin/sh -f

#set -x

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

inlib_mgr=../../../inexlib/inlib/mgr
exlib_mgr=../../../inexlib/exlib/mgr
ourex_mgr=../../../inexlib/ourex/mgr

build_pack=BatchLab_test_histo

. ${ourex_mgr}/build_header

if [ ${build_app} = "yes" ] ; then

  cppflags="${cppflags} -I.."
  cppflags="${cppflags} -I../../AIDA/v3r2p1"
  cppflags="${cppflags} -I${inlib_mgr}/.."
  cppflags="${cppflags} -I../../Lib/include"
  cppflags="${cppflags} -I../../Slash"

 #libs="${libs} -L${build_path} -lBatchLabAIDA"
 #libs="${libs} -L../../Lib/mgr/${build_dir} -lLibUtils"
 #libs="${libs} -L../../Minuit/mgr/${build_dir} -losc_Minuit"
 #libs="${libs} -L${ourex_mgr}/../zlib/${build_dir} -lourex_zlib"

  # enforce archives :
  libs="${libs} ${build_path}/libBatchLabAIDA.a"
  libs="${libs} ../../Lib/mgr/${build_dir}/libLibUtils.a"
  libs="${libs} ../../Minuit/mgr/${build_dir}/libosc_Minuit.a"
  libs="${libs} ${ourex_mgr}/../zlib/${build_dir}/libourex_zlib.a"

  if [ `uname` = "Linux" ] ; then libs="${libs} -ldl"; fi

  objs=
  app_exe=test_histo
  app_src=../tests/BatchLab_test_histo.cxx
  . ${inlib_mgr}/build_app

fi

. ${inlib_mgr}/build_clean
