#!/bin/sh -f

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

inlib_mgr=../../../inexlib/inlib/mgr
exlib_mgr=../../../inexlib/exlib/mgr
ourex_mgr=../../../inexlib/ourex/mgr

build_pack=BatchLabAIDA

. ${ourex_mgr}/build_header

if [ ${build_compile} = "yes" ] ; then

cppflags="${cppflags} -I.."
cppflags="${cppflags} -I../../Slash"
cppflags="${cppflags} -I../../AIDA/v3r2p1"
cppflags="${cppflags} -I../../Lib/include"
cppflags="${cppflags} -I../../amanip/src/cpp"
cppflags="${cppflags} -I../../Minuit"

cppflags="${cppflags} -I${inlib_mgr}/.."
cppflags="${cppflags} -I${exlib_mgr}/.."

cxxfiles=
cxxfiles="${cxxfiles} ../BatchLab/Core/AIDA.cxx"

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////
use_zlib=yes

zlib_home=${ourex_mgr}/../zlib

. ${exlib_mgr}/use_zlib

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

libname=libBatchLabAIDA
. ${inlib_mgr}/build_compile

fi # end build_compile
 
if [ ${build_archive} = "yes" ] ; then . ${inlib_mgr}/build_archive; fi

. ${inlib_mgr}/build_clean
