#!/bin/sh -f

#set -x

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

inlib_mgr=../../../inexlib/inlib/mgr
exlib_mgr=../../../inexlib/exlib/mgr
ourex_mgr=../../../inexlib/ourex/mgr

build_pack=BatchLabHBOOK

. ${ourex_mgr}/build_header

if [ ${build_compile} = "yes" ] ; then

cppflags="${cppflags} -I.."
cppflags="${cppflags} -I../../Slash"
cppflags="${cppflags} -I../../AIDA/v3r2p1"
cppflags="${cppflags} -I../../Lib/include"
cppflags="${cppflags} -I../../amanip/src/cpp"

cppflags="${cppflags} -I${inlib_mgr}/.."

cxxfiles=
cxxfiles="${cxxfiles} ../source/HBOOK/HBOOK.cxx"

libname=libBatchLabHBOOK

. ${inlib_mgr}/build_compile

fi # end build_compile
 
if [ ${build_archive} = "yes" ] ; then . ${inlib_mgr}/build_archive; fi

. ${inlib_mgr}/build_clean
