#!/bin/sh -f

#set -x

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

. ../mgr/build_header

if [ ${build_compile} = "yes" ] ; then

use_gtk=yes
. ${exlib_mgr}/use_gtk

if [ `uname` = Linux ] ; then
  ccflags="${ccflags} -fPIC"
fi

ccflags="${ccflags} -I./gtkgl"

cfiles="${cfiles} ./source/gdkgl.c"
cfiles="${cfiles} ./source/gtkglarea.c"

. ${inlib_mgr}/build_compile

fi # end build_compile
 
if [ ${build_archive} = "yes" ] ; then . ${inlib_mgr}/build_archive; fi

. ${inlib_mgr}/build_clean
