#!/bin/sh -f
#
#  To produce wrappers using SWIG.
#

exlib_mgr=../../../inexlib/exlib/mgr
inlib_mgr="${exlib_mgr}/../../inlib/mgr"
ourex_mgr="${exlib_mgr}/../../ourex/mgr"

use_swig=yes
. ${exlib_mgr}/use_swig

if [ ! -x ${swig_exe} ] ; then
  echo "swig program not found."
  exit
fi

pivy_home="${ourex_mgr}/../pivy"

incs=
incs="${incs} -I${pivy_home} -I${pivy_home}/fake_headers"
incs="${incs} -I${pivy_home}/interfaces"

incs="${incs} -I../../Slash"
incs="${incs} -I../../OnX/include"

incs="${incs} -I${ourex_mgr}/../CoinGL/include"
incs="${incs} -I${ourex_mgr}/../CoinPython"
incs="${incs} -I${ourex_mgr}/../HEPVis/include"
incs="${incs} -I${ourex_mgr}/../CoinPython/source"
incs="${incs} -I${ourex_mgr}/../HEPVis/source/SWIG"
incs="${incs} -I${inlib_mgr}/.."
incs="${incs} -I${inlib_mgr}/../inlib/histo"
incs="${incs} -I${inlib_mgr}/../inlib"

incs="${incs} -I../source/SWIG"

flags="-includeall -modern -D__PIVY__"
flags="${flags} -w302,306,307,312,389,361,362,467,503,509,510"
flags="${flags} -fcompact"

out_file=../source/Python/OnX_SWIG_Python.ic
eval ${swig_exe} -interface OnX_SWIG_Python -python -c++ ${flags} ${incs} -o ${out_file} ../source/SWIG/OnX_SWIG.i
/bin/mv ../source/Python/OnX.py ../scripts/Python/.

sed -e 's#PyErr_Format(PyExc_RuntimeError, mesg)#PyErr_Format(PyExc_RuntimeError, "%s",mesg)#g' ${out_file} > tmp;mv tmp ${out_file}

