#!/bin/sh -f

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

inlib_mgr=../../../inexlib/inlib/mgr
exlib_mgr=../../../inexlib/exlib/mgr
ourex_mgr=../../../inexlib/ourex/mgr

. ${ourex_mgr}/build_header

plugin=OnX

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////
if [ ${build_compile} = "yes" ] ; then

cppflags="${cppflags} -I${inlib_mgr}/.."
cppflags="${cppflags} -I../../Slash"
cppflags="${cppflags} -I../../Lib/include"

cxxfiles="${cxxfiles} ../source/Callbacks/AccessorAccessor.cxx"
cxxfiles="${cxxfiles} ../source/Callbacks/SoNodeAccessor.cxx"
cxxfiles="${cxxfiles} ../source/Callbacks/SessionCallbacks.cxx"
cxxfiles="${cxxfiles} ../source/Callbacks/Callbacks.cxx"
cxxfiles="${cxxfiles} ../source/Callbacks/EditExec.cxx"
cxxfiles="${cxxfiles} ../source/Callbacks/SceneHandler.cxx"
cxxfiles="${cxxfiles} ../source/Callbacks/IB.cxx"

# with Inventor :
cxxfiles="${cxxfiles} ../source/Callbacks/Viewer.cxx"
cxxfiles="${cxxfiles} ../source/Callbacks/Deprecated.cxx"
cxxfiles="${cxxfiles} ../source/Callbacks/SceneGraphAccessor.cxx"
cxxfiles="${cxxfiles} ../source/Callbacks/Page.cxx"
cxxfiles="${cxxfiles} ../source/Callbacks/Region.cxx"
cxxfiles="${cxxfiles} ../source/Callbacks/Plotter.cxx"
cxxfiles="${cxxfiles} ../source/Callbacks/InputFont.cxx"
cxxfiles="${cxxfiles} ../source/Callbacks/InputPlotter.cxx"
cxxfiles="${cxxfiles} ../source/Callbacks/InputAxis.cxx"

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

libs="${libs} -L../../Lib/mgr/${build_dir} -lLibUtils"

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////
use_HEPVis=yes
use_CoinGL=yes
use_GL=yes
use_png=yes
use_jpeg=yes
use_freetype=yes
use_zlib=yes

. ${exlib_mgr}/use_HEPVis
. ${exlib_mgr}/use_CoinGL
. ${exlib_mgr}/use_GL
. ${exlib_mgr}/use_png
. ${exlib_mgr}/use_jpeg
. ${exlib_mgr}/use_freetype
. ${exlib_mgr}/use_zlib

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

. ${inlib_mgr}/build_compile

fi # end build_compile
 
if [ ${build_plugin} = "yes" ] ; then . ${inlib_mgr}/build_plugin; fi

. ${inlib_mgr}/build_clean
