#!/bin/sh -f

#set -x

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

inlib_mgr=../../../inexlib/inlib/mgr
exlib_mgr=../../../inexlib/exlib/mgr
ourex_mgr=../../../inexlib/ourex/mgr

build_pack=OnXInventor

. ${ourex_mgr}/build_header

if [ ${build_compile} = "yes" ] ; then

cppflags="${cppflags} -I../include"
cppflags="${cppflags} -I../../Slash"

cxxfiles=
cxxfiles="${cxxfiles} ../source/Inventor/Inventor.cxx"
cxxfiles="${cxxfiles} ../source/Inventor/HEPVis.cxx"

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////
use_CoinGL=yes
CoinGL_home=${ourex_mgr}/../CoinGL
. ${exlib_mgr}/use_CoinGL

use_HEPVis=yes
HEPVis_home=${ourex_mgr}/../HEPVis
. ${exlib_mgr}/use_HEPVis
#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

libname=libOnXInventor
. ${inlib_mgr}/build_compile

fi # end build_compile
 
if [ ${build_archive} = "yes" ] ; then . ${inlib_mgr}/build_archive; fi

. ${inlib_mgr}/build_clean
