#!/bin/sh -f

build_args=
while test $# -ge 1 ; do build_args="${build_args} $1";shift; done

inlib_mgr=../../../inexlib/inlib/mgr
exlib_mgr=../../../inexlib/exlib/mgr
ourex_mgr=../../../inexlib/ourex/mgr

. ${ourex_mgr}/build_header

build_pack=plugin_OnX_SWIG_Python
plugin=OnX_SWIG_Python
pyname=OnX_SWIG_Python

if [ ${build_compile} = "yes" ] ; then

cppflags="${cppflags} -I${inlib_mgr}/.."
cppflags="${cppflags} -I../../Slash"

cxxfiles="${cxxfiles} ../source/Python/OnX_SWIG_Python.cxx"

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

libs="${libs} -L${build_path} -lOnXCore"
libs="${libs} -L../../Lib/mgr/${build_dir} -lLibUtils"

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

use_CoinPython=yes
use_Python=yes
use_HEPVis=yes
use_CoinGL=yes
use_GL=yes
use_expat=yes
use_jpeg=yes
use_png=yes
use_freetype=yes
use_zlib=yes

. ${exlib_mgr}/use_CoinPython
. ${exlib_mgr}/use_Python
. ${exlib_mgr}/use_HEPVis
. ${exlib_mgr}/use_CoinGL
. ${exlib_mgr}/use_GL
. ${exlib_mgr}/use_expat
. ${exlib_mgr}/use_jpeg
. ${exlib_mgr}/use_png
. ${exlib_mgr}/use_freetype
. ${exlib_mgr}/use_zlib

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////

. ${inlib_mgr}/build_compile

fi # end build_compile
 
if [ ${build_plugin} = "yes" ] ; then . ${inlib_mgr}/build_plugin; fi

. ${inlib_mgr}/build_clean
