/**************************************************************************
 *
 *  This file is part of the Coin GUI binding libraries.
 *  Copyright (C) 2000 by Systems in Motion.  All rights reserved.
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public License
 *  version 2.1 as published by the Free Software Foundation.  See the
 *  file LICENSE.LGPL at the root directory of the distribution for
 *  more details.
 *
 *  If you want to use Coin GUI bindings for applications not compatible
 *  with the LGPL, please contact SIM to acquire a Professional Edition
 *  License.
 *
 *  Systems in Motion, Prof Brochs gate 6, N-7030 Trondheim, NORWAY
 *  http://www.sim.no/ support@sim.no Voice: +47 22114160 Fax: +47 22207097
 *
 **************************************************************************/

/* Autogenerated from materials/artdeco/artdeco.0 */

#ifndef SOGTK_SILKY6_IV_H
#define SOGTK_SILKY6_IV_H

static const char silky6_iv[] =
  "#Inventor V1.0 ascii\n"
  "\n"
  "Material {\n"
  "	ambientColor	0.17114518 0.17079423 0.17152666\n"
  "	diffuseColor	0.68456549 0.68319218 0.68613717\n"
  "	specularColor	0.18233005 0.54081025 0.02615396\n"
  "	emissiveColor	0 0 0\n"
  "	shininess	0.07142748\n"
  "	transparency	0\n"
  "}\n"
;

#endif /* ! SOXT_ARTDECO0_IV_H */
