#!/bin/sh -f

args=
while test $# -ge 1 ; do args="${args} $1";shift;done

#gldum hbook md5 o2scl xercesc

packs=
packs="${packs} Minuit Rio AIDA Slash amanip Lib BatchLab UseAIDA"
packs="${packs} OnX OnXLab"
packs="${packs} osc_vis osc_batch"

save_dir="`pwd`"

for pack in ${packs} ; do
  echo "do ${pack} ..."
  cd ${save_dir}/${pack}/mgr
  #./build ${args}
  #./build -android -v -clean
  #./build -gnu
  _upgrade
done

