#!/bin/sh -f

version=17.0

build_args=

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////
inlib_mgr=../../../inexlib/inlib/mgr
ourex_mgr=../../../inexlib/ourex/mgr

. ${ourex_mgr}/build_header

save_dir=`pwd`
cd ${build_path}/distrib/osc_vis/${version}
./install
. ./setup.sh
use_Python=yes
. ./Resources/exlib/mgr/use_Python
echo ${Python_home}
cd ${save_dir}
