#!/bin/sh -f

#
# WARNING : the python program must be the one coming from the Python installation
#           used to build the plugins ([Coin,HEPVis,OnX,OnXLab]_SWIG_Python.so).
#           You must be aware that multiple python programs may exist on your machine.
#           On macOS, you must use the "pythonw" program.
#

version="`./version`"

run_what=
run_gui=
run_gdb=no

run_expat_debug=no
verbose_x=no
do_ls=no

build_args=
while test $# -ge 1 ; do
  case $1 in
        -gtk) run_gui=Gtk;;  
         -Qt) run_gui=Qt;;  
         -Xt) run_gui=Xt;;  
         -Xm) run_gui=Xt;;  
   -NextStep) run_gui=NextStep;;
        -gdb) run_gdb=yes;;
          -x) verbose_x=yes;;
         -ls) do_ls=yes;;
   
  -expat_debug) run_expat_debug=yes;;
	
          -*) build_args="${build_args} $1";;  
           *) run_what=$1;;  
  esac
  shift
done

if [ ${verbose_x} = yes ] ; then set -x;fi

#////////////////////////////////////
#////////////////////////////////////
#////////////////////////////////////
inlib_mgr=../../../inexlib/inlib/mgr
ourex_mgr=../../../inexlib/ourex/mgr

. ${ourex_mgr}/build_header

save_dir=`pwd`

#//////////////////////////////////////////
#//////////////////////////////////////////
#//////////////////////////////////////////

cd ${build_path}/distrib/osc_vis/${version}
./install
. ./setup.sh

#use_Python=yes
#. ./Resources/exlib/mgr/use_Python   # to get py_exe.

. ./py-setup.sh

. ./Python-setup.sh

#printenv PYTHONPATH
# if using the Qt driver :
#use_Qt=yes
#. ./Resources/exlib/mgr/use_Qt
#if [ "${Qt_ld_library_path}" != "" ] ; then
#  ld_path="${Qt_ld_library_path}"
#  . ./Resources/inlib/mgr/build_ld_library_path
#fi
#if [ "${Qt_plugin_path}" != "" ] ; then
#  setenv QT_PLUGIN_PATH "${Qt_plugin_path}"
#fi

. ./Qt-setup.sh

#////////////////////////////////////
#/// run : //////////////////////////
#////////////////////////////////////

OSC_ARGS="-balance"
export OSC_ARGS

if [ "${run_gui}" != "" ] ; then
  OSC_GUI_TOOLKIT=${run_gui}
  export OSC_GUI_TOOLKIT
  #if [ "${run_gui}" = "Gtk" ] ; then
  #  LC_CTYPE=C;export LC_CTYPE
  #fi
fi

if [ "${run_what}" = "" ] ; then run_what=AIDA/examples/Python/aida_0; fi

what_dir="`dirname ${run_what}`"
what_name="`basename ${run_what}`"
cd ./Resources/${what_dir}

if [ ${do_ls} = yes ] ; then
  ls
fi

if [ ${run_expat_debug} = yes ] ; then
  export LD_LIBRARY_PATH=".:${LD_LIBRARY_PATH}"
  cp /lib64/libexpat.so.1 .
fi

options=
#options=-i

if [ ${run_gdb} = yes ] ; then
  echo "gdb> r ${options} ${what_name}.py"
  gdb ${Python_exe}
else    
  ${Python_exe} ${options} ${what_name}.py
fi

cd ${OSC_HOME_DIR}

cd ${save_dir}
