#!/bin/sh -f

version="`../../osc_source/version`"

run_gui=
run_gdb=no
run_args=
build_args=

run_viewer=no
run_gui_viewer=no

while test $# -ge 1 ; do
  case $1 in
    -gnu)     build_args="${build_args} $1";;
    -intel)   build_args="${build_args} $1";;
    -clang)   build_args="${build_args} $1";;
    -visual)  build_args="${build_args} $1";;
    -sdk_mac) build_args="${build_args} $1";;

    -gtk)     run_gui=Gtk;;  
    -Qt)      run_gui=Qt;;  
    -qt)      run_gui=Qt;;  
    -Xt)      run_gui=Xt;;  
    -xt)      run_gui=Xt;;  
    -Xm)      run_gui=Xt;;  
    -xm)      run_gui=Xt;;  
   -Win)      run_gui=Win;;  
   -win)      run_gui=Win;;  
   -NextStep) run_gui=NextStep;;  
   -ns)       run_gui=NextStep;;  
   -SDL)      run_gui=SDL;;

    # local options : 
         -gdb) run_gdb=yes;;
      -viewer) run_viewer=yes;;
  -gui_viewer) run_gui_viewer=yes;;

    -*) run_args="${run_args} $1";;  
     *) run_args="${run_args} $1";;  
  esac
  shift
done

inlib_mgr=../../../inexlib/inlib/mgr
exlib_mgr=../../../inexlib/exlib/mgr
ourex_mgr=../../../inexlib/ourex/mgr

. ${ourex_mgr}/build_header # to get build_path

save_dir="`pwd`"

#//////////////////////////////////////////
#//////////////////////////////////////////
#//////////////////////////////////////////

cd ${build_path}/distrib/osc_vis/${version}
./install

. ./setup.sh

if [ "${run_gui}" = "Qt" ] ; then
  . ./Qt-setup.sh    
fi

if [ "${run_gui}" = "Gtk" ] ; then
  if [ "`printenv LANG`" = "" ] ; then
    LANG=en_US.US-ASCII;export LANG
  fi
fi

#//////////////////////////////////////////
#//////////////////////////////////////////
#//////////////////////////////////////////

LC_CTYPE=C;export LC_CTYPE

if [ ${run_viewer} = yes ] ; then
  osc-viewer -${run_gui} ${run_args}
elif [ ${run_gui_viewer} = yes ] ; then
  osc-gui-viewer -${run_gui} ${run_args} ${OSC_HOME_DIR}/Resources/OnX/examples/OnX/progress.onx
else
  if [ ${run_gdb} = yes ] ; then
    gdb osc-plot
  else
    osc-plot -${run_gui} ${run_args}
  fi
fi

cd ${save_dir}

