/**************************************************************************
 *
 *  This file is part of the Coin GUI binding libraries.
 *  Copyright (C) 2000 by Systems in Motion.  All rights reserved.
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public License
 *  version 2.1 as published by the Free Software Foundation.  See the
 *  file LICENSE.LGPL at the root directory of the distribution for
 *  more details.
 *
 *  If you want to use Coin GUI bindings for applications not compatible
 *  with the LGPL, please contact SIM to acquire a Professional Edition
 *  License.
 *
 *  Systems in Motion, Prof Brochs gate 6, N-7030 Trondheim, NORWAY
 *  http://www.sim.no/ support@sim.no Voice: +47 22114160 Fax: +47 22207097
 *
 **************************************************************************/

/* Autogenerated from materials/artdeco/artdeco.0 */

#ifndef SOQT_SUMMER10_IV_H
#define SOQT_SUMMER10_IV_H

static const char summer10_iv[] =
  "#Inventor V1.0 ascii\n"
  "\n"
  "Material {\n"
  "	ambientColor	0.10551613 0.16905470 0.19157701\n"
  "	diffuseColor	0.40669871 0.65156023 0.73839932\n"
  "	specularColor	1.0 0.13159380 0.21857022\n"
  "	emissiveColor	0 0 0\n"
  "	shininess	0.84864576\n"
  "	transparency	0\n"
  "}\n"
;

#endif /* ! SOQT_ARTDECO0_IV_H */
