#!/bin/sh -f 

dir_pwd="`pwd`"

cd ..

find . -depth -name 'bin_obuild' -print -exec /bin/rm -R -f {} \;

# FIXME : directory to be removed :
find . -depth -name 'www'       -print -exec /bin/rm -R -f {} \;
find . -depth -name 'configure' -print -exec /bin/rm -R -f {} \;
find . -depth -name 'omake'     -print -exec /bin/rm -R -f {} \;
find . -depth -name 'trash'     -print -exec /bin/rm -R -f {} \;
find . -depth -name 'mdset'     -print -exec /bin/rm -R -f {} \;
find . -depth -name 'Visual'    -print -exec /bin/rm -R -f {} \;
find . -depth -name 'mds'       -print -exec /bin/rm -R -f {} \;
find . -depth -name 'xcode'     -print -exec /bin/rm -R -f {} \;
find . -depth -name 'user'      -print -exec /bin/rm -R -f {} \;
find . -depth -name 'doc'       -print -exec /bin/rm -R -f {} \;
#find . -depth -name 'tools'     -print -exec /bin/rm -R -f {} \;

# remove cmt directories but not the one under Interfaces :
#/bin/mv Interfaces ../.
find . -depth -name 'cmt'       -print -exec /bin/rm -R -f {} \;
#/bin/mv ../Interfaces .

echo "Have to cleanup by hands AIDA by keeping only src/cpp."

# Some file not in the distrib :
find . -name 'gb_setup.*' -print -exec /bin/rm -f {} \;
find . -name 'rmason.cxx' -print -exec /bin/rm -f {} \;
find . -name 'BatchLab_exa_rmason.cxx' -print -exec /bin/rm -f {} \;
find . -name '*.pyc' -print -exec /bin/rm -f {} \;

# Some file not in the distrib :

if [ -d inlib ] ; then
  cd inlib
  /bin/rm -f inlib/sys/date
  cd ..
fi

if [ -d HEPVis ] ; then
  cd HEPVis
  /bin/rm -f INSTALL_NOTES
  /bin/rm -f GNUmakefile
  /bin/rm -f PLATFORMS
  /bin/rm -f README.srt
  /bin/rm -f RELNOTES
  /bin/rm -f examples/hepvis_text_hershey.cpp
  /bin/rm -f examples/hepvis_text_ttf.cpp
  /bin/rm -R -f ups
  /bin/rm -R -f install
  /bin/rm -f include/HEPVis/SDL
  /bin/rm -f applications/SDL
  cd ..
fi

if [ -d OnX ] ; then
  cd OnX
  /bin/rm -R -f examples/CINT
  /bin/rm -R -f scripts/DOS
  /bin/rm -R -f scripts/Xm
  /bin/rm -R -f scripts/xrm
  /bin/rm -R -f scripts/upgrade
  /bin/rm -R -f source/SDL
  /bin/rm -R -f include/OnX/SDL
  cd ..
fi

if [ -d OnXLab ] ; then
  cd OnXLab
  /bin/rm -R -f templates
  /bin/rm -R -f examples/CINT
  /bin/rm -R -f examples/ROOT
  /bin/rm -R -f examples/mathematica
  # we keep OnXLab_exa_config.cxx
  /bin/rm -f examples/cpp/OnXLab_exa_func_0.c
  /bin/rm -f examples/cpp/OnXLab_exa_func_1.c
  /bin/rm -f examples/cpp/OnXLab_exa_func_rmason.cpp
  cd ..
fi

if [ -d G4Lab ] ; then
  cd G4Lab
  /bin/rm -R -f scripts/DOS
  /bin/rm -R -f scripts/sh
  /bin/rm -R -f scripts/Help
  /bin/rm -R -f scripts/Python
  /bin/rm -R -f scripts/Styles
  /bin/rm -R -f scripts/Tcl
  /bin/rm -R -f scripts/XML
  /bin/rm -R -f scripts/Geant4
  cd ..
fi
  
# rm Tcl :
if [ -d OnX ] ; then
  cd OnX
  /bin/rm -R -f source/Tcl
  /bin/rm -R -f examples/Tcl
  /bin/rm -R -f tests/Tcl
  /bin/rm -R -f scripts/Tcl
  cd ..
fi
if [ -d OnXLab ] ; then
  cd OnXLab
  /bin/rm -R -f source/Tcl
  /bin/rm -R -f examples/Tcl
  /bin/rm -R -f scripts/Tcl
  cd ..
fi

# rm Java :
if [ -d OnX ] ; then
  cd OnX/obuild
  find . -name '*Java*' -exec /bin/rm -f {} \;
  cd ..
  /bin/rm -R -f source/Java
  /bin/rm -R -f examples/Java
  /bin/rm -R -f tests/Java
  /bin/rm -R -f examples/Python/Lib.py
  cd ..
fi

if [ -d OnXLab ] ; then
  cd OnXLab/obuild
  find . -name '*Java*' -exec /bin/rm -f {} \;
  cd ..
  /bin/rm -R -f source/Java
  /bin/rm -R -f examples/Java
  cd ..
fi

if [ -d OpenPAW ] ; then
  cd OpenPAW
  /bin/rm -R -f examples/C_PAW
  /bin/rm -R -f examples/OpenPAW
  /bin/rm -R -f examples/PAW
  /bin/rm -f examples/users/opaw_rfabbri_vec_op.kumac
  cd ..
fi
  
if [ -d steve ] ; then
  cd steve
  /bin/rm -R -f examples/exa_5
  /bin/rm -R -f examples/exa_6
  cd ..
fi

if [ -d obuild ] ; then
  cd obuild
  /bin/rm -R -f ./release
  cd ..
fi

if [ -d osc_source ] ; then
  cd osc_source/release/UNIX
  /bin/rm -R -f SDL-setup.sh
  /bin/rm -R -f SDL-setup.csh
  cd ../../..
fi

if [ -d osc_batch ] ; then
  cd osc_batch/obuild
  /bin/rm -R -f obuild_setup.sh
  /bin/rm -R -f obuild_setup.csh
  cd ../..
fi

if [ -d osc_vis ] ; then
  cd osc_vis/obuild
  /bin/rm -R -f obuild_setup.sh
  /bin/rm -R -f obuild_setup.csh
  cd ../..
fi

cd ${dir_pwd}
