#!/bin/sh -f 

dir_pwd="`pwd`"

vers=`cat version`

zip_file=osc_vis_source_${vers}.zip

cd ..
cp ${dir_pwd}/osc_vis_README README

cd ..
/bin/rm -f ${zip_file}
zip -q -r ${zip_file} OpenScientist

cd ${dir_pwd}

