#!/bin/sh -f 

dir_pwd="`pwd`"

#vers=`cat version`
vers=0.1

zip_file=osc_steve_source_${vers}.zip

cd ..
cp ${dir_pwd}/osc_steve_README README

cd ..
/bin/rm -f ${zip_file}

packs=""

# FIXME : handle the below list through a this.obuild.

packs="${packs} OpenScientist/README"
packs="${packs} OpenScientist/obuild"
packs="${packs} OpenScientist/foreign"

packs="${packs} OpenScientist/zlib"
packs="${packs} OpenScientist/zip"
packs="${packs} OpenScientist/HDF5"
packs="${packs} OpenScientist/steve"

packs="${packs} OpenScientist/osc_source"
packs="${packs} OpenScientist/osc_steve"

for pack in ${packs}
do 
  if [ ! -e ${pack} ] ; then
    echo "${pack} not found."
    exit
  fi
done

zip -q -r ${zip_file} ${packs}

cd ${dir_pwd}

