#!/bin/sh -f

#set -x

what=
version=
host=
if [ $# -ne 3 ] ; then
  echo 'Three arguments expected :'
  echo '  UNIX> osc_build_remote <kit> <version> <host>'
  exit
else
  what=$1
  version=$2
  host=$3
fi

build_remote() {
a_what=$1
a_version=$2
a_host=$3

if [ ${a_host} = pano ] ; then
  remote=barrand@pc-panoramix.lal.in2p3.fr
  scp ./osc_wget_build ${remote}:.
  ssh ${remote} ./osc_wget_build -what ${a_what} -version ${a_version}
elif [ ${a_host} = macppc ] ; then
  remote=barrand@mac-91114.lal.in2p3.fr
  scp ./osc_wget_build ${remote}:.
  ssh ${remote} ./osc_wget_build -what ${a_what} -version ${a_version}
elif [ ${a_host} = macintel ] ; then
  remote=barrand@wl-72136.lal.in2p3.fr
  scp ./osc_wget_build ${remote}:.
  ssh ${remote} ./osc_wget_build -what ${a_what} -version ${a_version}
elif [ ${a_host} = lx64 ] ; then
  remote=gybarran@lxplus.cern.ch
  scp ./osc_wget_build ${remote}:.
  ssh ${remote} ./osc_wget_build -what ${a_what} -version ${a_version}
elif [ ${a_host} = cygwin ] ; then
  remote=administrateur@nb-barrand.lal.in2p3.fr
  scp ./osc_wget_build ${remote}:.
  ssh ${remote} ./osc_wget_build -what ${a_what} -version ${a_version}
elif [ ${a_host} = win ] ; then
  remote=administrateur@nb-barrand.lal.in2p3.fr
  dir_work=/cygdrive/c/
  # Avoid to have the cygwin bin by default 
  # in PATH when starting the DOS session.
  # For example f77.exe may exist too under cygwin bin.
  dos_path=/cygdrive/c/WINDOWS/System32
  scp ./osc_wget_build.bat ${remote}:${dir_work}/.
  ssh ${remote} "cd ${dir_work};PATH="${dos_path}";cmd /c osc_wget_build.bat ${a_what} ${a_version}"
else
  echo "Unknown host ${a_host}."
fi

}

if [ ${what} = all ] ; then
  build_remote osc_obuild ${version} ${host}
  build_remote osc_batch  ${version} ${host}
  build_remote osc_vis    ${version} ${host}
  build_remote osc_g4     ${version} ${host}
else
  build_remote ${what}   ${version} ${host}
fi



