#!/bin/sh -f 

dir_pwd="`pwd`"

vers=`cat version`

zip_file=osc_iv_source_${vers}.zip

cd ..
cp ${dir_pwd}/osc_iv_README README

cd ..
/bin/rm -f ${zip_file}

packs=""

# FIXME : handle the below list through a this.obuild.

packs="${packs} OpenScientist/README"
packs="${packs} OpenScientist/inlib"
packs="${packs} OpenScientist/exlib"
packs="${packs} OpenScientist/expat"
packs="${packs} OpenScientist/obuild"
packs="${packs} OpenScientist/foreign"
packs="${packs} OpenScientist/zlib"
packs="${packs} OpenScientist/zip"

packs="${packs} OpenScientist/png"
packs="${packs} OpenScientist/jpeg"
packs="${packs} OpenScientist/dvi2bitmap"
packs="${packs} OpenScientist/freetype2"
packs="${packs} OpenScientist/gtkglarea"

packs="${packs} OpenScientist/CoinGL"
packs="${packs} OpenScientist/CoinXt"
packs="${packs} OpenScientist/CoinWin"
packs="${packs} OpenScientist/CoinQt"
packs="${packs} OpenScientist/CoinGtk"
packs="${packs} OpenScientist/CoinNextStep"
packs="${packs} OpenScientist/CoinPython"
packs="${packs} OpenScientist/HEPVis"

packs="${packs} OpenScientist/survival"

packs="${packs} OpenScientist/osc_source"
packs="${packs} OpenScientist/osc_iv"

for pack in ${packs}
do 
  if [ ! -e ${pack} ] ; then
    echo "${pack} not found."
    exit
  fi
done

zip -q -r ${zip_file} ${packs}

cd ${dir_pwd}

