
G4ANALYSIS_USE=1
export G4ANALYSIS_USE

G4ANALYSIS_AIDA_CONFIG_CFLAGS=`aida-config --include`
export G4ANALYSIS_AIDA_CONFIG_CFLAGS

G4ANALYSIS_AIDA_CONFIG_LIBS=`aida-config --lib`
export G4ANALYSIS_AIDA_CONFIG_LIBS

G4VIS_NONE=1
export G4VIS_NONE

G4UI_NONE=1
export G4UI_NONE

unset G4LIB_USE_GRANULAR

G4LIB_BUILD_SHARED=1
export G4LIB_BUILD_SHARED


